import{a as y,S as g,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const h="50661357-54eafa09b89a1672a3d0f9999",b="https://pixabay.com/api/";async function L(s){const r={key:h,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await y.get(b,{params:r})).data}const l=document.querySelector(".gallery"),u=document.querySelector(".loader"),p=new g(".gallery a",{captionsData:"alt",captionDelay:250});p.on("closed.simplelightbox",()=>{document.body.style.overflow="auto"});function v(s){const r=s.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:i,comments:f,downloads:m})=>`<li class="gallery-item">
           <a href="${a}">
             <img src="${o}" alt="${e}" />
           </a>
           <div class="info">
             <p><b>Likes:</b> ${t}</p>
             <p><b>Views:</b> ${i}</p>
             <p><b>Comments:</b> ${f}</p>
             <p><b>Downloads:</b> ${m}</p>
           </div>
         </li>`).join("");l.insertAdjacentHTML("beforeend",r),p.refresh()}function q(){l.innerHTML=""}function w(){u.classList.add("visible")}function c(){u.classList.remove("visible")}const d=document.querySelector(".form"),S=d.querySelector('input[name="search-text"]');d.addEventListener("submit",async s=>{s.preventDefault();const r=S.value.trim();if(!r){n.warning({message:"Please enter your search query",position:"topRight"});return}q(),w();try{const o=await L(r);if(c(),!o.hits.length){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}v(o.hits)}catch(o){c(),n.error({message:"An error occurred, please try again later!",position:"topRight"}),console.error(o)}});
//# sourceMappingURL=index.js.map
