import{a as S,S as x,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const B="50661357-54eafa09b89a1672a3d0f9999",P="https://pixabay.com/api/";async function p(s,o=1){const r={key:B,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await S.get(P,{params:r})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more"),y=new x(".gallery a",{captionsData:"alt",captionDelay:250});y.on("closed.simplelightbox",()=>{document.body.style.overflow="auto"});function g(s){const o=s.map(({webformatURL:r,largeImageURL:i,tags:e,likes:t,views:n,comments:w,downloads:q})=>`<li class="gallery-item">
           <a href="${i}">
             <img src="${r}" alt="${e}" width="400px" height="250px"/>
           </a>
           <div class="info">
             <p><b>Likes:</b> ${t}</p>
             <p><b>Views:</b> ${n}</p>
             <p><b>Comments:</b> ${w}</p>
             <p><b>Downloads:</b> ${q}</p>
           </div>
         </li>`).join("");m.insertAdjacentHTML("beforeend",o),y.refresh()}function $(){m.innerHTML=""}function b(){f.classList.add("visible")}function l(){f.classList.remove("visible")}function E(){h.classList.remove("is-visible")}function u(){h.classList.add("is-visible")}const L=document.querySelector(".form"),M=L.querySelector('input[name="search-text"]'),R=document.querySelector(".load-more");let d="",c=1,v=0;L.addEventListener("submit",async s=>{s.preventDefault();const o=M.value.trim();if(!o){a.warning({message:"Please enter your search query",position:"topRight"});return}d=o,c=1,$(),u(),b();try{const r=await p(d,c);if(v=r.totalHits,l(),!r.hits.length){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(r.hits)}catch(r){l(),a.error({message:"An error occurred, please try again later!",position:"topRight"}),console.error(r)}});R.addEventListener("click",async()=>{c+=1,b(),u();try{const s=await p(d,c);g(s.hits),l();const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*4,behavior:"smooth"}),c*15>=v?(a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),u()):E()}catch(s){l(),a.error({message:"An error occurred while loading the next page.",position:"topRight"}),console.error(s)}});
//# sourceMappingURL=index.js.map
