import{a as x,S as B,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const P="50661357-54eafa09b89a1672a3d0f9999",$="https://pixabay.com/api/";async function f(s,o=1){const r={key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await x.get($,{params:r})).data}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),g=new B(".gallery a",{captionsData:"alt",captionDelay:250});g.on("closed.simplelightbox",()=>{document.body.style.overflow="auto"});function b(s){const o=s.map(({webformatURL:r,largeImageURL:n,tags:e,likes:t,views:a,comments:q,downloads:S})=>`<li class="gallery-item">
           <a href="${n}">
             <img src="${r}" alt="${e}" width="400px" height="250px"/>
           </a>
           <div class="info">
             <p><b>Likes:</b> ${t}</p>
             <p><b>Views:</b> ${a}</p>
             <p><b>Comments:</b> ${q}</p>
             <p><b>Downloads:</b> ${S}</p>
           </div>
         </li>`).join("");h.insertAdjacentHTML("beforeend",o),g.refresh()}function E(){h.innerHTML=""}function L(){m.classList.add("visible")}function l(){m.classList.remove("visible")}function v(){y.classList.remove("hidden")}function u(){y.classList.add("hidden")}const w=document.querySelector(".form"),M=w.querySelector('input[name="search-text"]'),R=document.querySelector(".load-more");let d="",i=1,p=0;w.addEventListener("submit",async s=>{s.preventDefault();const o=M.value.trim();if(!o){c.warning({message:"Please enter your search query",position:"topRight"});return}d=o,i=1,E(),u(),L();try{const r=await f(d,i);if(p=r.totalHits,l(),!r.hits.length){c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(r.hits),p>i*15&&v()}catch(r){l(),c.error({message:"An error occurred, please try again later!",position:"topRight"}),console.error(r)}});R.addEventListener("click",async()=>{i++,L(),u();try{const s=await f(d,i);b(s.hits),l();const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),i*15>=p?(c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),u()):v()}catch(s){l(),c.error({message:"An error occurred while loading the next page.",position:"topRight"}),console.error(s)}});
//# sourceMappingURL=index.js.map
